app:
    resource: '@AppBundle/Controller/'
    type: annotation

courses:
  path: /courses/{page}
  defaults: {_controller: 'AppBundle:Courses:List', page: 1}

details:
  path: /courses/{number}
  defaults: {_controller: 'AppBundle:Courses:Details'}
  requirements:
    number: '\d+'


studentsCreate:
  resource: '@AppBundle/Controller/'
  type: annotation

studentsGet:
  resource: '@AppBundle/Controller/'
  type: annotation

apropos:
  path: /a-propos
  defaults:  {_controller: 'AppBundle:Apropos'}
  requirements:
    _local: fr|en